/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: FilipMatlak (https://sketchfab.com/FilipMatlak)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/baseball-cap-f0a58aef4fe84e89a327e676e62c1b00
Title: Baseball Cap
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Cap1(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert3SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')

export default Cap1;