/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Cap10.gltf 
Author: oluwaphemi (https://sketchfab.com/oluwaphemi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bucket-hat-5206aa93bce448a8b936ce763cfc245d
Title: Bucket Hat
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Cap10.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material51829.001']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material51956.001']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material51709.002']} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material51709.002']} />
      <mesh geometry={nodes.Object_17.geometry} material={materials['Material51709.002']} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['Material51709.002']} />
      <mesh geometry={nodes.Object_23.geometry} material={materials['Material51709.002']} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Material51709.002']} />
      <mesh geometry={nodes.Object_29.geometry} material={materials['Material51709.002']} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Material51709.002']} />
      <mesh geometry={nodes.Object_35.geometry} material={materials['Material51709.002']} />
      <mesh geometry={nodes.Object_37.geometry} material={materials['Denim_Lightweight_FRONT_51502.001']} />
      <mesh geometry={nodes.Object_39.geometry} material={materials['Denim_Lightweight_FRONT_51502.001']} />
      <mesh geometry={nodes.Object_41.geometry} material={materials['Denim_Lightweight_FRONT_51502.001']} />
      <mesh geometry={nodes.Object_43.geometry} material={materials['Denim_Lightweight_FRONT_51502.001']} />
    </group>
  )
}

useGLTF.preload('/Cap10.gltf')
