/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Cap1.gltf
Author: butterstotch (https://sketchfab.com/butterstotch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/baseball-cap-ny-b7ecae3e46554ef4ab0b43ee97106e04
Title: Baseball Cap NY
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cap1(props) {
  const { nodes, materials } = useGLTF('/Cap1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.004']} position={[0.001, -0.797, -0.016]} rotation={[0.013, 0, -Math.PI]} scale={[-1, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/Cap1.gltf')