/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Cap2.gltf 
Author: tunahandemiircii (https://sketchfab.com/tunahandemiircii)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soldier-cap-9034559b8bdd48ddacace6c481b0b7e0
Title: Soldier Cap
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cap2(props) {
  const { nodes, materials } = useGLTF('/Cap2.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.cap_bottom_low__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.button__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.cap_bottom_low001__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.cap_bottom_low003__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.cap_bottom_low005__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube001__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Cap2.gltf')
