/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Cap4.gltf 
Author: SparkiL (https://sketchfab.com/sparkilambda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tokoyami-towas-cap-4fb9681973e841209810c607560dede6
Title: Tokoyami Towa's Cap
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Cap4.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.ButtonLarge} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.ButtonSmall} />
        <lineSegments geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Ring} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Ring} />
      </group>
    </group>
  )
}

useGLTF.preload('/Cap4.gltf')
