/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Cap8.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cat-cap-0abe1e46f1de423c937e92a2af1e4124
Title: Cat Cap
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Cap8.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} scale={[1, 1, 0.895]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.001']} position={[-0.704, 0.421, 0.002]} rotation={[0, 0, 2.611]} scale={[0.032, 0.076, 0.076]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_13.geometry} material={materials['Material.001']} position={[0.017, 0.032, 0]} />
    </group>
  )
}

useGLTF.preload('/Cap8.gltf')
