/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Cap9.gltf 
Author: 64verti (https://sketchfab.com/64verti)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skengman-beanie-cap-f55382cb9f704b32a2874ab898493cdf
Title: SKENGMAN BEANIE CAP
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Cap9.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[2.152, 0.196, 1.179]} rotation={[-0.435, 0, 0]}>
          <group position={[-2.164, 0, 0]}>
            <group position={[-0.137, -0.436, -0.149]} rotation={[0, 0.077, 0]} scale={1.196}>
              <group position={[0.497, 2.229, 0.938]} rotation={[1.418, 0.018, -0.558]} scale={[0.179, 0.179, 0.328]}>
                <mesh geometry={nodes.pasted__polySurface4_pasted__aiStandardSurface3_0.geometry} material={materials.pasted__aiStandardSurface3} position={[0.01, -0.013, -0.006]} rotation={[0, 0, -0.042]} scale={[0.959, 1, 1.13]} />
              </group>
              <mesh geometry={nodes.pasted__polySurface3_pasted__aiStandardSurface2_0.geometry} material={materials.pasted__aiStandardSurface2} position={[-0.261, 2.182, 0.807]} rotation={[1.324, -0.02, 0.45]} scale={[0.272, 0.063, 0.238]} />
            </group>
            <group position={[0.083, -0.48, -0.212]} scale={1.215}>
              <mesh geometry={nodes.pasted__polySurface5_pasted__aiStandardSurface3_0.geometry} material={materials.pasted__aiStandardSurface3} position={[0.485, 2.223, 0.928]} rotation={[1.42, 0.03, -0.682]} scale={[0.16, 0.167, 0.364]} />
              <mesh geometry={nodes.pasted__polySurface2_pasted__aiStandardSurface2_0.geometry} material={materials.pasted__aiStandardSurface2} position={[-0.302, 2.183, 0.815]} rotation={[1.324, -0.02, 0.45]} scale={[0.272, 0.063, 0.238]} />
            </group>
          </group>
          <mesh geometry={nodes.pasted__pSphere1_pasted__aiStandardSurface1_0.geometry} material={materials.pasted__aiStandardSurface1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Cap9.gltf')
